spring.datasource.url=jdbc:postgresql://dpg-d6uof2ua2pns73fmfr6g-a.singapore-postgres.render.com/moneymanager_gb90
spring.datasource.username=moneymanager_gb90_user
spring.datasource.password=99oashn1assnSouUmB9iTKVm6Ki1u2uI