spring.datasource.url=jdbc:postgresql://money_manager_2ot5_user:kZ2MvT4rf4suXpIwlsSWKXXGc6vn8Oc3@dpg-d87b6g9s16ns738ttol0-a.singapore-postgres.render.com/money_manager_2ot5
spring.datasource.username=money_manager_2ot5_user
spring.datasource.password=kZ2MvT4rf4suXpIwlsSWKXXGc6vn8Oc3
